CREATE TABLE dim_cuenta(
	dim_id_cuenta NUMBER PRIMARY KEY,
	ID_CUENTA NUMBER,
	NUMERO_CUENTA NUMBER(30),
	FECHA_APERTURA DATE,
	-- Status cuenta
	ID_STATUS_CUENTA NUMBER,	
	DESCRIPCION_STATUS VARCHAR(500),
	-- tipo cuenta
	ID_TIPO_CUENTA NUMBER,
	DESCRIPCION_TIPO VARCHAR(500),
	REQUISITOS_TIPO VARCHAR(500)
);

CREATE SEQUENCE cuenta
INCREMENT BY 1
START WITH 1;

--

CREATE TABLE dim_sucursal(
	dim_id_sucursal NUMBER PRIMARY KEY,
	ID_SUCURSAL NUMBER,
	DESCRIPCION VARCHAR(500),
	RIF VARCHAR(500),
	TELEFONO VARCHAR(500),
	FAX VARCHAR(500)
);

CREATE SEQUENCE sucursal
INCREMENT BY 1
START WITH 1;

--

CREATE TABLE dim_cliente(
	dim_id_cliente NUMBER PRIMARY KEY,
	ID_CLIENTE NUMBER,
	CI VARCHAR(500),
	NOMBRE VARCHAR(500),
	APELLIDO VARCHAR(500),
	RIF VARCHAR(500),
	CORREO VARCHAR(500),
	EDAD NUMBER,
	SEXO VARCHAR(3),
	DIRECCION VARCHAR(500),
	-- Estado civil
	ID_ESTADO_CIVIL NUMBER,
	DESCRIPCION_ESTADO_CIVIL NUMBER,
	-- Datos crediticios
	ID_DATOS_CREDITICIOS NUMBER,	
	ESTE_BANCO CHAR,
	MONTO_PEDIDO NUMBER(22,6),
	TASA_INTERES NUMBER(22,6),
	CANT_PLAZOS NUMBER (22,6),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	STATUS_CREDITO VARCHAR2(10)
);

CREATE SEQUENCE cliente
INCREMENT BY 1
START WITH 1;

--

CREATE TABLE dim_producto_financiero(
	dim_id_producto_financiero NUMBER PRIMARY KEY,
	ID_PRODUCTO_FINANCIERO NUMBER,
	DESCRIPCION VARCHAR(500),
	BENEFICIOS VARCHAR(500)
);

CREATE SEQUENCE producto_financiero
INCREMENT BY 1
START WITH 1;

--

CREATE TABLE dim_tipo_transaccion(
	dim_id_tipo_transaccion NUMBER PRIMARY KEY,
	ID_TIPO_TRANSACCION NUMBER,
	DESCRIPCION VARCHAR(500),
	INTERES NUMBER(22,6),
	PORCENTAJE NUMBER(22,6)
);

CREATE SEQUENCE tipo_transaccion 
INCREMENT BY 1
START WITH 1;

--

CREATE TABLE dim_grupo_familiar(
	dim_id_grupo_familiar NUMBER PRIMARY KEY,
	DESCRIPCION VARCHAR(500),
	CANT_PERSONAS_FAMILIA NUMBER,
	MENORES CHAR,
	CANT_MENORES NUMBER,
	-- Datos demograficos
	ID_DATOS_DEMOGRAFICOS NUMBER,
	ID_GRUPO_FAMILIAR NUMBER,
	CANT_PERSONAS NUMBER,
	EDAD_PROMEDIO NUMBER(22,6),
	UBICACION VARCHAR(500),
	TIPO_VIVIENDA VARCHAR(500),
	TIPO_ZONA VARCHAR(500),
	CLASE_SOCIAL VARCHAR(500),
	INGRESO_MENSUAL NUMBER(22,6)
);

CREATE SEQUENCE grupo_familiar 
INCREMENT BY 1
START WITH 1;

--

CREATE TABLE dim_tiempo(
	dim_id_tiempo number PRIMARY KEY,
	-- Año
	ano number,
	id_ano number,
	desc_ano varchar2(100),
	-- Mes
	mes varchar2(10),
	id_mes number, 
	desc_mes varchar2(100),
	fecha_completa date
);