DROP TABLE marca CASCADE CONSTRAINTS;
DROP TABLE categoria CASCADE CONSTRAINTS;
DROP TABLE subcategoria CASCADE CONSTRAINTS;
DROP TABLE producto CASCADE CONSTRAINTS;
DROP TABLE estado CASCADE CONSTRAINTS;
DROP TABLE ciudad CASCADE CONSTRAINTS;
DROP TABLE tienda CASCADE CONSTRAINTS;
DROP TABLE proveedor CASCADE CONSTRAINTS;
DROP TABLE almacen CASCADE CONSTRAINTS;
DROP TABLE tiene CASCADE CONSTRAINTS;
DROP TABLE almacena CASCADE CONSTRAINTS;
DROP TABLE abastece CASCADE CONSTRAINTS;
DROP TABLE provee CASCADE CONSTRAINTS;

DROP TABLE dim_producto CASCADE CONSTRAINTS;
DROP TABLE dim_tienda CASCADE CONSTRAINTS;
DROP TABLE almacen CASCADE CONSTRAINTS;
DROP TABLE dim_tiempo CASCADE CONSTRAINTS;
DROP TABLE dim_proveedor CASCADE CONSTRAINTS;
DROP TABLE fact_table_n1 CASCADE CONSTRAINTS;
DROP TABLE fact_table_n1 CASCADE CONSTRAINTS;

DROP TABLESPACE fuente INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE fuente_temporal INCLUDING CONTENTS AND DATAFILES;
DROP USER FUENTE CASCADE;

DROP TABLESPACE dw INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE dw_temporal INCLUDING CONTENTS AND DATAFILES;
DROP USER DATAW CASCADE;

COMMIT;