--- Creando las tablas del modelo relacional

CREATE TABLE ESTADO_CIVIL(
	ID_ESTADO_CIVIL NUMBER,
	DESCRIPCION VARCHAR(500),
	CONSTRAINT ESTADO_CIVIL_PK PRIMARY KEY(ID_ESTADO_CIVIL)
);

CREATE TABLE GRUPO_FAMILIAR(
	ID_GRUPO_FAMILIAR NUMBER,
	DESCRIPCION VARCHAR(500),
	CANT_PERSONAS_FAMILIA NUMBER,
	MENORES CHAR,
	CANT_MENORES NUMBER,
	CONSTRAINT GRUPO_FAMILIAR_PK PRIMARY KEY(ID_GRUPO_FAMILIAR)
);

CREATE TABLE DATOS_DEMOGRAFICOS(
	ID_DATOS_DEMOGRAFICOS NUMBER,
	ID_GRUPO_FAMILIAR NUMBER,
	CANT_PERSONAS NUMBER,
	EDAD_PROMEDIO NUMBER(22,6),
	UBICACION VARCHAR(500),
	TIPO_VIVIENDA VARCHAR(500),
	TIPO_ZONA VARCHAR(500),
	CLASE_SOCIAL VARCHAR(500),
	INGRESO_MENSUAL NUMBER(22,6),
	CONSTRAINT DATDEM_PK PRIMARY KEY(ID_DATOS_DEMOGRAFICOS),
	CONSTRAINT DATDEM_GRUPO_FK FOREIGN KEY(ID_GRUPO_FAMILIAR) REFERENCES GRUPO_FAMILIAR(ID_GRUPO_FAMILIAR)
);

CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER,
	CI VARCHAR(500),
	NOMBRE VARCHAR(500),
	APELLIDO VARCHAR(500),
	RIF VARCHAR(500),
	CORREO VARCHAR(500),
	EDAD NUMBER,
	SEXO VARCHAR(3),
	DIRECCION VARCHAR(500),
	ID_ESTADO_CIVIL NUMBER,
	CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE),
	CONSTRAINT ESTADO_CIVIL_FK FOREIGN KEY(ID_ESTADO_CIVIL) REFERENCES ESTADO_CIVIL(ID_ESTADO_CIVIL)
);

CREATE TABLE SUCURSAL(
	ID_SUCURSAL NUMBER,
	DESCRIPCION VARCHAR(500),
	RIF VARCHAR(500),
	TELEFONO VARCHAR(500),
	FAX VARCHAR(500),
	CONSTRAINT SUCURSAL_PK PRIMARY KEY(ID_SUCURSAL)
);

CREATE TABLE TIPO_CUENTA(
	ID_TIPO_CUENTA NUMBER,
	DESCRIPCION_TC VARCHAR(500),
	REQUISITOS VARCHAR(500),
	CONSTRAINT TIPO_CUENTA_PK PRIMARY KEY(ID_TIPO_CUENTA)
);

CREATE TABLE STATUS_CUENTA(
	ID_STATUS_CUENTA NUMBER,
	DESCRIPCION_ST VARCHAR(500),
	CONSTRAINT STATUS_CUENTA_PK PRIMARY KEY(ID_STATUS_CUENTA)
);

CREATE TABLE CUENTA(
	ID_CUENTA NUMBER,
	NUMERO_CUENTA NUMBER(30),
	FECHA_APERTURA DATE,
	ID_TIPO_CUENTA NUMBER,
	ID_SUCURSAL NUMBER,
	ID_STATUS_CUENTA NUMBER,
	CONSTRAINT CUENTA_PK PRIMARY KEY(ID_CUENTA),
	CONSTRAINT TIPO_CUENTA_FK FOREIGN KEY(ID_TIPO_CUENTA) REFERENCES TIPO_CUENTA(ID_TIPO_CUENTA),
	CONSTRAINT SUCURSAL_FK FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL),
	CONSTRAINT STATUS_CUENTA_FK FOREIGN KEY(ID_STATUS_CUENTA) REFERENCES STATUS_CUENTA(ID_STATUS_CUENTA)
);

CREATE TABLE ESTADO_CUENTA(
	ID_ESTADO_CUENTA NUMBER,
	DESCRIPCION VARCHAR(500),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	SALDO_FAVOR NUMBER(22,6),
	CANT_MOVIMIENTOS NUMBER,
	DEUDA NUMBER(22,6),
	CONSTRAINT ESTADO_CUENTA_PK PRIMARY KEY(ID_ESTADO_CUENTA)
);

CREATE TABLE PRODUCTO_FINANCIERO(
	ID_PRODUCTO_FINANCIERO NUMBER,
	DESCRIPCION VARCHAR(500),
	BENEFICIOS VARCHAR(500),
	CONSTRAINT PRODUCTO_PK PRIMARY KEY(ID_PRODUCTO_FINANCIERO)
);

CREATE TABLE TIPO_TRANSACCION(
	ID_TIPO_TRANSACCION NUMBER,
	DESCRIPCION VARCHAR(500),
	INTERES NUMBER(22,6),
	PORCENTAJE NUMBER(22,6),
	CONSTRAINT TIPO_TRANSACCION_PK PRIMARY KEY(ID_TIPO_TRANSACCION)
);

CREATE TABLE TRANSACCION(
	ID_TRANSACCION NUMBER,
	ID_CUENTA NUMBER,
	ID_CLIENTE NUMBER,
	ID_PRODUCTO_FINANCIERO NUMBER,
	ID_TIPO_TRANSACCION NUMBER,
	FECHA DATE,
	DESCRIPCION VARCHAR(500),
	MONTO NUMBER(22,6),
	IMPUESTO NUMBER(22,6),
	CONSTRAINT TRANSACCION_PK PRIMARY KEY(ID_TRANSACCION),
	CONSTRAINT TRANS_CUENTA_FK FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA),
	CONSTRAINT TRANS_PRODUCTO_FK FOREIGN KEY(ID_PRODUCTO_FINANCIERO) REFERENCES PRODUCTO_FINANCIERO(ID_PRODUCTO_FINANCIERO),
	CONSTRAINT TRANS_TIPO_FK FOREIGN KEY(ID_TIPO_TRANSACCION) REFERENCES TIPO_TRANSACCION(ID_TIPO_TRANSACCION)
);

--- Relaciones

--- ENTRE CUENTA Y CLIENTE
CREATE TABLE PERTENECE(
	ID_CLIENTE NUMBER,
	ID_CUENTA NUMBER,
	ID_SUCURSAL NUMBER,
	FECHA DATE,
	CONSTRAINT PERT_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT PERT_SUCURSAL_FK FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL),
	CONSTRAINT PERT_CUENTA_FK FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
);
--- ENTRE CUENTA Y PRODUCTO FINANCIERO
CREATE TABLE TIENE(
	ID_PRODUCTO_FINANCIERO NUMBER,
	ID_CUENTA NUMBER,
	CONSTRAINT TIENE_PRODUCTO_FK FOREIGN KEY(ID_PRODUCTO_FINANCIERO) REFERENCES PRODUCTO_FINANCIERO(ID_PRODUCTO_FINANCIERO),
	CONSTRAINT TIENE_CUENTA_FK FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
);
--- ENTRE CUENTA Y ESTADO DE CUENTA
CREATE TABLE POSEE(
	ID_CUENTA NUMBER,
	ID_ESTADO_CUENTA NUMBER,
	DETALLE VARCHAR(500),
	CONSTRAINT POSEE_CUENTA_FK FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA),
	CONSTRAINT POSEE_EST_CUENTA_FK FOREIGN KEY(ID_ESTADO_CUENTA) REFERENCES ESTADO_CUENTA(ID_ESTADO_CUENTA)
);
--- ENTRE ESTADO DE CUENTA Y TRANSACCION
CREATE TABLE REFLEJA(
	ID_ESTADO_CUENTA NUMBER,
	ID_TRANSACCION NUMBER,
	FECHA DATE,
	SALDO NUMBER(22,6),
	CONSTRAINT REF_EST_CUENTA_FK FOREIGN KEY(ID_ESTADO_CUENTA) REFERENCES ESTADO_CUENTA(ID_ESTADO_CUENTA),
	CONSTRAINT REF_TRANS_FK FOREIGN KEY(ID_TRANSACCION) REFERENCES TRANSACCION(ID_TRANSACCION)
);
--- ENTRE GRUPO FAMILIAR Y CLIENTE
CREATE TABLE CONFORMA(
	ID_CLIENTE NUMBER,
	ID_GRUPO_FAMILIAR NUMBER,
	JEFE_GRUPO CHAR,
	CONSTRAINT CONF_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT CONF_GRUPO_FK FOREIGN KEY(ID_GRUPO_FAMILIAR) REFERENCES GRUPO_FAMILIAR(ID_GRUPO_FAMILIAR)
);
--- ENTRE GRUPO FAMILIAR Y CUENTA
CREATE TABLE AGRUPA(
	ID_GRUPO_FAMILIAR NUMBER,
	ID_CUENTA NUMBER,
	CONSTRAINT AGR_GRUPO_FK FOREIGN KEY(ID_GRUPO_FAMILIAR) REFERENCES GRUPO_FAMILIAR(ID_GRUPO_FAMILIAR),
	CONSTRAINT AGR_CUENTA_FK FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
);

