CREATE TABLE EXCEL(
	ID_DATOS_CREDITICIOS NUMBER PRIMARY KEY,
	ESTE_BANCO CHAR,
	ID_CLIENTE NUMBER (22,6),
	MONTO_PEDIDO NUMBER(22,6),
	TASA_INTERES NUMBER(22,6),
	CANT_PLAZOS NUMBER (22,6),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	STATUS_CREDITO VARCHAR2(10)
);

COMMIT;