DROP TABLESPACE TRANSACCIONAL INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE TRANSACCIONAL DATAFILE 'TRANSACCIONAL_DATAF.DBF' SIZE 200M;
DROP USER TRANS CASCADE;
CREATE USER TRANS IDENTIFIED BY jadr123;
ALTER USER TRANS QUOTA UNLIMITED ON TRANSACCIONAL;
ALTER USER TRANS DEFAULT TABLESPACE TRANSACCIONAL;

DROP TABLESPACE INTERMEDIA INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE INTERMEDIA DATAFILE 'INTERMEDIA_DATAF.DBF' SIZE 200M;
DROP USER INTER CASCADE;
CREATE USER INTER IDENTIFIED BY jadr123;
ALTER USER INTER QUOTA UNLIMITED ON INTERMEDIA;
ALTER USER INTER DEFAULT TABLESPACE INTERMEDIA;
GRANT ALL PRIVILEGES TO INTER;



DROP TABLESPACE DW2 INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE DW2 DATAFILE 'DW2_DATAF.DBF' SIZE 400M;
DROP USER UDW2 CASCADE;
CREATE USER UDW2 IDENTIFIED BY jadr123;
ALTER USER UDW2 DEFAULT TABLESPACE UDW2;
GRANT ALL PRIVILEGES TO UDW2;

GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO TRANS;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO INTER;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO DATAW2;

CONNECT TRANS/jadr123;
@'C:\Users\Jean\Desktop\Laboratorio2\SCRIPTS\cre_transaccional.sql'
@'C:\Users\Jean\Desktop\Laboratorio2\SCRIPTS\insert_transaccional.sql'

CONNECT INTER/jadr123;
@'C:\Users\Jean\Desktop\Laboratorio2\SCRIPTS\cre_intermedio.sql'