CREATE TABLE SEXO(
	COD_SEXO		NUMBER(8),
	DESCRIPCION 	VARCHAR2(20),
	CONSTRAINT SEXO_PK PRIMARY KEY(COD_SEXO)
);

CREATE TABLE ESTADO_CIVIL(
	COD_EST_CIVIL 	NUMBER(8),
	DESCRIPCION_EC 	VARCHAR(20),
	CONSTRAINT ESTADO_CIVIL_PK PRIMARY KEY(COD_EST_CIVIL)
);

CREATE TABLE TIPO_PERSONA(
	COD_TIP_PERS	NUMBER(8),
	DESCRIPCION_TP		VARCHAR2(255),
	BENEFICIOS_tp		VARCHAR2(255),
	CONSTRAINT TIPO_PERSONA_PK PRIMARY KEY(COD_TIP_PERS)
);

CREATE TABLE TIPO_EMPLEADO(
	COD_TIP_EMP		NUMBER(8),
	DESCRIPCION_TE		VARCHAR2(255),
	FUNCIONES_TE		VARCHAR2(510),
	CONSTRAINT TIPO_EMP_PK PRIMARY KEY(COD_TIP_EMP)
);

CREATE TABLE ESTADO(
	COD_ESTADO		NUMBER(8),
	NOMBRE_ESTADO	VARCHAR2(255),
	COD_POSTAL_E		VARCHAR2(6),
	CONSTRAINT ESTADO_PK PRIMARY KEY(COD_ESTADO)
);

CREATE TABLE CIUDAD(
	COD_CIUDAD		NUMBER(8),
	NOMBRE_CIUDAD	VARCHAR2(255),
	COD_POSTAL_C		VARCHAR2(6),
	COD_ESTADO		NUMBER(8),
	CONSTRAINT CIUDAD_PK PRIMARY KEY(COD_CIUDAD),
	CONSTRAINT ESTADO_FK FOREIGN KEY(COD_ESTADO) REFERENCES ESTADO(COD_ESTADO)
);

CREATE TABLE SUCURSAL(
	COD_SUCURSAL 	NUMBER(8),
	NOMBRE_SUCURSAL VARCHAR2(255),
	RIF				VARCHAR2(20),
	TELEFONO		VARCHAR2(20),
	FAX				VARCHAR2(20),
	DIRECCION_SUCURSAL		VARCHAR2(510),
	COD_CIUDAD		NUMBER(8),
	CONSTRAINT SUCURSAL_PK PRIMARY KEY(COD_SUCURSAL),
	CONSTRAINT CIUDAD_FK FOREIGN KEY(COD_CIUDAD) REFERENCES CIUDAD(COD_CIUDAD)
);

CREATE TABLE EMPLEADO(
	COD_EMPLEADO	NUMBER(8),
	COD_TIP_EMP		NUMBER(8),
	CEDULA			VARCHAR2(20),
	RIF_E 			VARCHAR2(20),
	NOMBRE 			VARCHAR2(500),
	APELLIDO 		VARCHAR2(500),
	COD_SEXO 		NUMBER(8),
	COD_EST_CIVIL 	NUMBER(8),
	EDAD 			NUMBER,
	CORREO		    VARCHAR2(100),
	COD_CIUDAD		NUMBER(8),
	DIRECCION 		VARCHAR2(500),
	COD_SUCURSAL	NUMBER(8),
	CONSTRAINT EMPLEADO_PK PRIMARY KEY(COD_EMPLEADO),
	CONSTRAINT TIPO_EMP_FK FOREIGN KEY(COD_TIP_EMP) REFERENCES TIPO_EMPLEADO(COD_TIP_EMP),
	CONSTRAINT SEXO_EMP_FK FOREIGN KEY(COD_SEXO) REFERENCES SEXO(COD_SEXO),
	CONSTRAINT EST_CIV_EMP_FK FOREIGN KEY(COD_EST_CIVIL) REFERENCES ESTADO_CIVIL(COD_EST_CIVIL),
	CONSTRAINT CIUDAD_EMP_FK FOREIGN KEY(COD_CIUDAD) REFERENCES CIUDAD(COD_CIUDAD),
	CONSTRAINT SUCURSAL_EMP_FK FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL)
);

CREATE TABLE ASEGURADO(
	COD_ASEGURADO	NUMBER(8),
	COD_TIP_PERS	NUMBER(8),
	CEDULA_A		VARCHAR2(20),
	RIF_A 			VARCHAR2(20),
	NOMBRE 			VARCHAR2(500),
	APELLIDO 		VARCHAR2(500),
	COD_SEXO 		NUMBER(8),
	COD_EST_CIVIL 	NUMBER(8),
	EDAD_ASEGURADO 	NUMBER,
	CORREO		    VARCHAR2(100),
	COD_CIUDAD		NUMBER(8),
	DIRECCION 		VARCHAR2(500),
	COD_SUCURSAL	NUMBER(8),
	CONSTRAINT ASEGURADO_PK PRIMARY KEY(COD_ASEGURADO),
	CONSTRAINT TIPO_ASEG_FK FOREIGN KEY(COD_TIP_PERS) REFERENCES TIPO_PERSONA(COD_TIP_PERS),
	CONSTRAINT SEXO_ASEG_FK FOREIGN KEY(COD_SEXO) REFERENCES SEXO(COD_SEXO),
	CONSTRAINT EST_CIV_ASEG_FK FOREIGN KEY(COD_EST_CIVIL) REFERENCES ESTADO_CIVIL(COD_EST_CIVIL),
	CONSTRAINT CIUDAD_ASEG_FK FOREIGN KEY(COD_CIUDAD) REFERENCES CIUDAD(COD_CIUDAD),
	CONSTRAINT SUCURSAL_ASEG_FK FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL)
);

CREATE TABLE TIPO_POLIZA(
	COD_TIPO_POLIZA	NUMBER(8),
	NOMB_TIP_POLIZA	VARCHAR2(255),
	DESCRIPCION		VARCHAR2(255),
	REQUISITOS		VARCHAR2(510),
	CONSTRAINT TIPO_POLIZA_PK PRIMARY KEY(COD_TIPO_POLIZA)
);

CREATE TABLE FORMA_PAGO(
	COD_FORMA_PAGO	NUMBER(8),
	DESCRIPCION		VARCHAR2(255),
	CONSTRAINT FORMA_PAGO_PK PRIMARY KEY(COD_FORMA_PAGO)
);

CREATE TABLE SERVICIO(
	COD_SERVICIO	NUMBER(8),
	COD_TIPO_POLIZA	NUMBER(8),
	NOMBRE_SERVICIO	VARCHAR2(255),
	DESCRIPCION_SERVICIO		VARCHAR2(255),
	BENEFICIOS		VARCHAR2(510),
	CONSTRAINT SERVICIO_PK PRIMARY KEY(COD_SERVICIO),
	CONSTRAINT TIPO_POL_SERV_FK FOREIGN KEY(COD_TIPO_POLIZA) REFERENCES TIPO_POLIZA(COD_TIPO_POLIZA)
);

CREATE TABLE STATUS_POLIZA(
	COD_STATUS_POL	NUMBER(8),
	DESCRIPCION_SP	VARCHAR2(255),
	CONSTRAINT STATUS_POLIZA_PK PRIMARY KEY(COD_STATUS_POL)
);

CREATE TABLE POLIZA(
	COD_POLIZA 		NUMBER(8),
	COD_TIPO_POLIZA	NUMBER(8),
	DESCRIPCION_POLIZA		VARCHAR2(510),
	COD_STATUS_POL	NUMBER(8),
	COD_ASEGURADO	NUMBER(8),
	COD_EMPLEADO	NUMBER(8),
	COD_FORMA_PAGO	NUMBER(8),
	COD_SUCURSAL	NUMBER(8),
	SUMA_ASEGURADA	NUMBER(22,6),
	FECHA_APERTURA	DATE,
	VIGENTE_HASTA	DATE,
	CONSTRAINT POLIZA_PK PRIMARY KEY(COD_POLIZA),
	CONSTRAINT STATUS_POLIZA_FK FOREIGN KEY(COD_STATUS_POL) REFERENCES STATUS_POLIZA(COD_STATUS_POL),
	CONSTRAINT POLIZA_ASEG_FK FOREIGN KEY(COD_ASEGURADO) REFERENCES ASEGURADO(COD_ASEGURADO),
	CONSTRAINT POLIZA_EMP_FK FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
	CONSTRAINT POLIZA_FP_FK FOREIGN KEY(COD_FORMA_PAGO) REFERENCES FORMA_PAGO(COD_FORMA_PAGO),
	CONSTRAINT POLIZA_SUC_FK FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL)
);

CREATE TABLE VEHICULO(
	COD_VEHICULO	NUMBER(8),
	COD_POLIZA		NUMBER(8),
	CLASE			VARCHAR2(210),
	MARCA			VARCHAR2(210),
	MODELO			VARCHAR2(210),
	ANIO			VARCHAR2(4),
	VERSION			VARCHAR2(210),
	COLOR			VARCHAR2(210),
	PLACA			VARCHAR2(210),
	CONSTRAINT VEHICULO_PK PRIMARY KEY(COD_VEHICULO),
	CONSTRAINT POLIZA_VEHI_FK FOREIGN KEY(COD_POLIZA) REFERENCES POLIZA(COD_POLIZA)
);

CREATE TABLE CAUSA_SIN(
	COD_CAUSA_SIN	NUMBER(8),
	DESCRIPCION		VARCHAR2(210),
	CONSTRAINT CAUSA_PK PRIMARY KEY(COD_CAUSA_SIN)
);

CREATE TABLE TIPO_SINIESTRO(
	COD_TIPO_SIN	NUMBER(8),
	DESCRIPCION		VARCHAR2(210),
	COD_TIPO_POLIZA	NUMBER(8),
	CONSTRAINT TIPO_SIN_PK PRIMARY KEY(COD_TIPO_SIN),
	CONSTRAINT TIPO_P_FK FOREIGN KEY(COD_TIPO_POLIZA) REFERENCES TIPO_POLIZA(COD_TIPO_POLIZA)
);

CREATE TABLE STATUS_SINIESTRO(
	COD_STATUS_SIN	NUMBER(8),
	DESCRIPCION		VARCHAR2(210),
	CONSTRAINT STATUS_SINIESTRO_PK PRIMARY KEY(COD_STATUS_SIN)
);

CREATE TABLE SINIESTRO_SALUD(
	COD_SIN_SALUD	NUMBER(8),
	COD_TIPO_SIN	NUMBER(8),
	COD_ASEGURADO	NUMBER(8),
	COD_POLIZA		NUMBER(8),
	COD_SUCURSAL	NUMBER(8),
	COD_EMPLEADO	NUMBER(8),
	COD_CAUSA_SIN	NUMBER(8),
	COD_STATUS_SIN	NUMBER(8),
	CARNET_MEDICO	VARCHAR2(10),
	CLINICA			NUMBER(8),
	FECHA_EXAMEN	DATE,
	DIAGNOSTICO		VARCHAR2(500),
	ESPECIALIDAD	VARCHAR2(500),
	MONTO_MEDICINA	NUMBER(22,6),
	MONTO_TOTAL		NUMBER(22,6),
	MONTO_A_PAGAR	NUMBER(22,6),
	MONTO_DEUDA		NUMBER(22,6),
	CONSTRAINT SINIESTRO_SALUD_PK PRIMARY KEY(COD_SIN_SALUD),
	CONSTRAINT TIP_SIN_SAL_FK FOREIGN KEY(COD_TIPO_SIN) REFERENCES TIPO_SINIESTRO(COD_TIPO_SIN),
	CONSTRAINT SIN_SAL_ASE_FK FOREIGN KEY(COD_ASEGURADO) REFERENCES ASEGURADO(COD_ASEGURADO),
	CONSTRAINT SIN_SAL_POL_FK FOREIGN KEY(COD_POLIZA) REFERENCES POLIZA(COD_POLIZA),
	CONSTRAINT SIN_SAL_SUC_FK FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL),
	CONSTRAINT SIN_SAL_EMP_FK FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
	CONSTRAINT SIN_SAL_STA_FK FOREIGN KEY(COD_STATUS_SIN) REFERENCES STATUS_SINIESTRO(COD_STATUS_SIN),
	CONSTRAINT SIN_SAL_CAU_FK FOREIGN KEY(COD_CAUSA_SIN) REFERENCES CAUSA_SIN(COD_CAUSA_SIN)
);

CREATE TABLE SINIESTRO_VEHICULO(
	COD_SIN_VEHI	NUMBER(8),
	COD_TIPO_SIN	NUMBER(8),
	COD_ASEGURADO	NUMBER(8),
	COD_POLIZA		NUMBER(8),
	COD_SUCURSAL	NUMBER(8),
	COD_EMPLEADO	NUMBER(8),
	COD_CAUSA_SIN	NUMBER(8),
	COD_VEHICULO	NUMBER(8),
	COD_STATUS_SIN	NUMBER(8),
	CARNET_PERITO	VARCHAR2(10),
	CENTRO_INSP		NUMBER(8),
	FECHA_INSPEC	DATE,
	RESULTADO		VARCHAR2(500),
	MONTO_REPUESTOS	NUMBER(22,6),
	MONTO_TOTAL		NUMBER(22,6),
	MONTO_A_PAGAR	NUMBER(22,6),
	MONTO_DEUDA		NUMBER(22,6),
	CONSTRAINT SINIESTRO_VEHI_PK PRIMARY KEY(COD_SIN_VEHI),
	CONSTRAINT TIP_SIN_VEH_FK FOREIGN KEY(COD_TIPO_SIN) REFERENCES TIPO_SINIESTRO(COD_TIPO_SIN),
	CONSTRAINT SIN_VEH_ASE_FK FOREIGN KEY(COD_ASEGURADO) REFERENCES ASEGURADO(COD_ASEGURADO),
	CONSTRAINT SIN_VEH_POL_FK FOREIGN KEY(COD_POLIZA) REFERENCES POLIZA(COD_POLIZA),
	CONSTRAINT SIN_VEH_SUC_FK FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL),
	CONSTRAINT SIN_VEH_EMP_FK FOREIGN KEY(COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
	CONSTRAINT SIN_VEH_CAU_FK FOREIGN KEY(COD_CAUSA_SIN) REFERENCES CAUSA_SIN(COD_CAUSA_SIN),
	CONSTRAINT SIN_VEH_STA_FK FOREIGN KEY(COD_STATUS_SIN) REFERENCES STATUS_SINIESTRO(COD_STATUS_SIN),
	CONSTRAINT SIN_VEH_VEH_FK FOREIGN KEY(COD_VEHICULO) REFERENCES VEHICULO(COD_VEHICULO)	
);